# fly.toml app configuration file for cf-hub backend
# Docs: https://fly.io/docs/reference/configuration/

app = "cf-hub-backend"
primary_region = "iad"

[build]
  # Uses Dockerfile in backend/

[env]
  NODE_ENV = "production"
  API_BASE_PATH = "/api"

# This block defines the service, its ports, and its health checks.
[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
  
  # This health check is now correctly associated with the service above.
  [[services.http_checks]]
    path = "/api/health" # Note: key is 'path', not 'http_path'
    grace_period = "10s"
    interval = "15s"
    method = "get"
    timeout = "2s"