# fly.toml app configuration file for cf-hub backend
# Docs: https://fly.io/docs/reference/configuration/

app = "cf-hub-backend"
primary_region = "iad" # change to a region near your DB (e.g., "sjc", "lhr")

[build]
  # Uses Dockerfile in backend/

[env]
  NODE_ENV = "production"
  API_BASE_PATH = "/api"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false   # keep always-on if you choose dedicated; Machines free tier may still scale to zero
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"

# Optional health check hitting /api/health
[[checks]]
  http_path = "/api/health"
  grace_period = "10s"
  interval = "15s"
  method = "get"
  timeout = "2s"
