import { GoogleGenerativeAI } from "@google/generative-ai";
import { NextResponse } from "next/server";

// Check if API key exists
if (!process.env.GOOGLE_API_KEY) {
	throw new Error("GOOGLE_API_KEY is not set in environment variables");
}

const genAI = new GoogleGenerativeAI(process.env.GOOGLE_API_KEY);
const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

const systemPrompt = `You are an AI assistant for CF Hub, a comprehensive career mentorship platform. Here's what you need to know:

1. About CF Hub:
   - A platform connecting students with industry professionals
   - Focuses on career development and mentorship
   - Provides guidance for various industries and career paths

2. Industries We Cover:
   - Investment Banking
   - Risk Management
   - Finance
   - Business Analytics
   - Brand Management
   - Demand Planning
   - Operations
   - Consulting
   - Technology

3. Program Features:
   - One-on-one mentorship sessions
   - Industry-specific guidance
   - Career path planning
   - Resume and interview preparation
   - Networking opportunities
   - Professional development workshops

4. Mentorship Process:
   - Initial consultation
   - Career assessment
   - Personalized development plan
   - Regular mentoring sessions
   - Progress tracking
   - Industry networking

5. Key Information to Provide:
   - Program details and requirements
   - Registration process
   - Mentorship benefits
   - Industry insights
   - Career development tips
   - Learning resources

6. Important Guidelines:
   - Always maintain a professional and supportive tone
   - Provide specific, actionable advice
   - Direct users to appropriate resources
   - If unsure about specific details, guide users to contact the support team
   - Emphasize the personalized nature of the mentorship program
   - Include information about both technical and soft skills development

7. Registration Process:
   - Visit the website
   - Create an account
   - Complete profile
   - Select preferred industry/mentor
   - Schedule initial consultation

Remember to:
- Be encouraging and supportive
- Provide practical, industry-specific advice
- Guide users toward making informed career decisions
- Maintain confidentiality and professionalism
- Direct users to the appropriate sections of the website for more information`;

export async function POST(req) {
	try {
		const { message } = await req.json();

		if (!message) {
			return NextResponse.json(
				{ error: "Message is required" },
				{ status: 400 }
			);
		}

		console.log("Sending request to Gemini with message:", message);

		// Initialize the chat with the system prompt
		const chat = model.startChat({
			history: [
				{
					role: "user",
					parts: [{ text: systemPrompt }],
				},
			],
			generationConfig: {
				temperature: 0.7,
				maxOutputTokens: 500,
			},
		});

		/**
		 * Send the message posted by the user to the Gemini model and read the
		 * response generated by the model.
		 */
		const result = await chat.sendMessage(message);
		const response = await result.response;
		const text = response.text();

		console.log("Received response from Gemini:", text);

		return NextResponse.json({ response: text });
	} catch (error) {
		console.error("Chat API Error Details:", {
			name: error.name,
			message: error.message,
			stack: error.stack,
		});

		return NextResponse.json(
			{
				error: "Failed to process chat request",
				message: error.message,
				details: "No additional details available",
			},
			{ status: 500 }
		);
	}
}
